// src/mockData.js
// This data is shown when Supabase is not yet connected.
// Once you set up Supabase (see src/supabase.js instructions), real data loads instead.

export const MOCK_HOSTELS = [
  {
    id: '1',
    name: 'The Grand Nomad',
    city: 'Lisbon',
    country: 'Portugal',
    description: 'A beautifully restored 19th-century townhouse in the heart of Alfama. Stone arches, azulejo tiles, and the smell of fresh pastéis de nata greet you every morning. The rooftop offers a 360° view of the city's terracotta rooftops.',
    price_per_night: 18,
    rating: 4.9,
    review_count: 312,
    image_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop',
    amenities: ['Free Breakfast', 'Rooftop Terrace', 'Bike Rental', 'Wine Tasting'],
    available_beds: 12,
  },
  {
    id: '2',
    name: 'Maison Bohème',
    city: 'Paris',
    country: 'France',
    description: 'Hidden in a cobblestone alley of Montmartre, this intimate hostel blends Haussmannian grandeur with bohemian warmth. Art on every wall. Jazz on Tuesday nights.',
    price_per_night: 32,
    rating: 4.8,
    review_count: 187,
    image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop',
    amenities: ['City Views', 'Bar & Lounge', 'Art Gallery', 'Guided Tours'],
    available_beds: 8,
  },
  {
    id: '3',
    name: 'Casa Vieja',
    city: 'Cartagena',
    country: 'Colombia',
    description: 'Colonial-era courtyard hostel draped in bougainvillea. The hammock garden is legendary. Sunsets from the rooftop are not optional.',
    price_per_night: 14,
    rating: 4.7,
    review_count: 428,
    image_url: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&auto=format&fit=crop',
    amenities: ['Pool', 'Hammock Garden', 'Rooftop Bar', 'Salsa Classes'],
    available_beds: 16,
  },
  {
    id: '4',
    name: 'The Silk Road Inn',
    city: 'Istanbul',
    country: 'Turkey',
    description: 'Steps from the Grand Bazaar, this Ottoman-era han has been welcoming travelers since 1887. Stained glass, hand-woven carpets, and tea served all day.',
    price_per_night: 22,
    rating: 4.8,
    review_count: 264,
    image_url: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&auto=format&fit=crop',
    amenities: ['Hammam', 'Rooftop', 'Turkish Breakfast', 'Bazaar Tours'],
    available_beds: 10,
  },
  {
    id: '5',
    name: 'The Navigator',
    city: 'Porto',
    country: 'Portugal',
    description: 'A maritime-themed retreat in the Ribeira district. Original wood beams, river views, and a cellar stocked with local port wine.',
    price_per_night: 20,
    rating: 4.6,
    review_count: 195,
    image_url: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&auto=format&fit=crop',
    amenities: ['River View', 'Wine Cellar', 'Free Port Tasting', 'Library'],
    available_beds: 9,
  },
  {
    id: '6',
    name: 'Kyoto House',
    city: 'Kyoto',
    country: 'Japan',
    description: 'A lovingly restored machiya townhouse in Gion. Tatami rooms, a garden koi pond, and morning matcha ceremony included with every stay.',
    price_per_night: 45,
    rating: 4.9,
    review_count: 512,
    image_url: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&auto=format&fit=crop',
    amenities: ['Matcha Ceremony', 'Garden', 'Tatami Rooms', 'Zen Meditation'],
    available_beds: 6,
  },
]

export const DESTINATIONS = ['All', 'Europe', 'Asia', 'Americas', 'Under €20']
